-- RS Connect v36.24.0 — inscrição pública do Plano Inicial com trial Asaas

CREATE TABLE IF NOT EXISTS public_signup_settings (
    id TINYINT UNSIGNED NOT NULL DEFAULT 1,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    gateway_id BIGINT UNSIGNED NULL,
    plan_key VARCHAR(80) NOT NULL DEFAULT 'starter',
    trial_days SMALLINT UNSIGNED NOT NULL DEFAULT 7,
    grace_days SMALLINT UNSIGNED NOT NULL DEFAULT 3,
    checkout_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 60,
    commercial_whatsapp VARCHAR(30) NULL,
    commercial_message VARCHAR(500) NULL,
    terms_url VARCHAR(500) NULL,
    privacy_url VARCHAR(500) NULL,
    updated_by_user_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_public_signup_gateway (gateway_id),
    KEY idx_public_signup_user (updated_by_user_id),
    CONSTRAINT fk_public_signup_gateway FOREIGN KEY (gateway_id) REFERENCES payment_gateways(id) ON DELETE SET NULL,
    CONSTRAINT fk_public_signup_user FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_signup_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    token_hash CHAR(64) NOT NULL,
    public_reference VARCHAR(100) NOT NULL,
    gateway_id BIGINT UNSIGNED NOT NULL,
    plan_id BIGINT UNSIGNED NOT NULL,
    company_name VARCHAR(150) NOT NULL,
    legal_name VARCHAR(190) NULL,
    responsible_name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    document VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NULL,
    amount DECIMAL(12,2) NOT NULL,
    status ENUM('started','checkout_created','checkout_completed','provisioned','expired','cancelled','failed') NOT NULL DEFAULT 'started',
    external_checkout_id VARCHAR(190) NULL,
    external_checkout_url TEXT NULL,
    external_customer_id VARCHAR(190) NULL,
    external_subscription_id VARCHAR(190) NULL,
    external_status VARCHAR(80) NULL,
    trial_days SMALLINT UNSIGNED NOT NULL DEFAULT 7,
    trial_starts_at DATE NULL,
    trial_ends_at DATE NULL,
    first_charge_at DATE NOT NULL,
    tenant_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    subscription_id BIGINT UNSIGNED NULL,
    accepted_terms_at DATETIME NOT NULL,
    accepted_privacy_at DATETIME NOT NULL,
    checkout_created_at DATETIME NULL,
    checkout_completed_at DATETIME NULL,
    provisioned_at DATETIME NULL,
    last_webhook_at DATETIME NULL,
    expires_at DATETIME NOT NULL,
    last_error TEXT NULL,
    payload_json JSON NULL,
    ip_hash CHAR(64) NULL,
    user_agent_hash CHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_public_signup_token (token_hash),
    UNIQUE KEY uq_public_signup_reference (public_reference),
    KEY idx_public_signup_email_status (email, status, created_at),
    KEY idx_public_signup_checkout (external_checkout_id),
    KEY idx_public_signup_customer (external_customer_id),
    KEY idx_public_signup_subscription (external_subscription_id),
    KEY idx_public_signup_tenant (tenant_id),
    CONSTRAINT fk_public_signup_session_gateway FOREIGN KEY (gateway_id) REFERENCES payment_gateways(id) ON DELETE RESTRICT,
    CONSTRAINT fk_public_signup_session_plan FOREIGN KEY (plan_id) REFERENCES saas_plans(id) ON DELETE RESTRICT,
    CONSTRAINT fk_public_signup_session_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL,
    CONSTRAINT fk_public_signup_session_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_public_signup_session_subscription FOREIGN KEY (subscription_id) REFERENCES tenant_subscriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_subscription_gateways (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    subscription_id BIGINT UNSIGNED NOT NULL,
    gateway_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(40) NOT NULL,
    external_checkout_id VARCHAR(190) NULL,
    external_customer_id VARCHAR(190) NULL,
    external_subscription_id VARCHAR(190) NULL,
    status VARCHAR(80) NULL,
    first_charge_at DATE NULL,
    last_event_at DATETIME NULL,
    payload_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_subscription_gateway_subscription (subscription_id),
    KEY idx_subscription_gateway_external (provider, external_subscription_id),
    KEY idx_subscription_gateway_customer (provider, external_customer_id),
    CONSTRAINT fk_subscription_gateway_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_gateway_subscription FOREIGN KEY (subscription_id) REFERENCES tenant_subscriptions(id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_gateway_gateway FOREIGN KEY (gateway_id) REFERENCES payment_gateways(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO public_signup_settings
    (id, enabled, plan_key, trial_days, grace_days, checkout_minutes, commercial_message, terms_url, privacy_url)
VALUES
    (1, 0, 'starter', 7, 3, 60,
     'Olá! Quero conhecer os planos Profissional e Empresarial da RS Connect.',
     '/termos-de-uso', '/politica-de-privacidade')
ON DUPLICATE KEY UPDATE id = VALUES(id);
