<?php

declare(strict_types=1);

return [
    'schema_snapshot' => [
        'file' => 'database/schema.sql',
        'through' => '004_crm.sql',
    ],
    'bootstrap_seed' => 'database/seed.sql',
    'seed' => 'database/seed.reference.sql',
    'rollbacks' => [
        '030_google_calendar_availability_modes_rollback.sql',
    ],
    'migrations' => [
        ['sequence' => 1, 'file' => '002_companies_users_onboarding.sql'],
        ['sequence' => 2, 'file' => '003_conversations.sql'],
        ['sequence' => 3, 'file' => '004_crm.sql'],
        ['sequence' => 4, 'file' => '005_ai_automations.sql'],
        ['sequence' => 5, 'file' => '006_switch_active_agents_to_openai.sql'],
        ['sequence' => 6, 'file' => '007_ai_commercial_rules.sql'],
        ['sequence' => 7, 'file' => '008_conversations_pro_crm_auto.sql'],
        ['sequence' => 8, 'file' => '009_calendar_appointments.sql'],
        ['sequence' => 9, 'file' => '010_n8n_tenant_flows.sql'],
        ['sequence' => 10, 'file' => '011_n8n_templates_callbacks.sql'],
        ['sequence' => 11, 'file' => '012_saas_billing_plans.sql'],
        ['sequence' => 12, 'file' => '013_payment_gateways.sql'],
        ['sequence' => 13, 'file' => '014_pagbank_billing_reminders.sql'],
        ['sequence' => 14, 'file' => '015_notifications_frontend_billing_templates.sql'],
        ['sequence' => 15, 'file' => '016_reports_realtime_conversations.sql'],
        ['sequence' => 16, 'file' => '017_evolution_qrcode_status.sql'],
        ['sequence' => 17, 'file' => '017_pre_scheduling_tenant_menus.sql'],
        ['sequence' => 18, 'file' => '018_onboarding_prompt_builder.sql'],
        ['sequence' => 19, 'file' => '018_pre_schedule_messages_confirmation.sql'],
        ['sequence' => 20, 'file' => '019_implementation_checklist.sql'],
        ['sequence' => 21, 'file' => '019_pre_schedule_confirmation_rules.sql'],
        ['sequence' => 22, 'file' => '020_pre_schedule_reliable_capture.sql'],
        ['sequence' => 23, 'file' => '020_queue_team_distribution.sql'],
        ['sequence' => 24, 'file' => '021_campaigns_controlled_broadcasts.sql'],
        ['sequence' => 25, 'file' => '021_security_system.sql'],
        ['sequence' => 26, 'file' => '022_lgpd_privacy_acceptance.sql'],
        ['sequence' => 27, 'file' => '022_white_label_basic.sql'],
        ['sequence' => 28, 'file' => '023_operations_monitoring_backup.sql'],
        ['sequence' => 29, 'file' => '023_white_label_pro.sql'],
        ['sequence' => 30, 'file' => '024_operations_alerts_backup_details.sql'],
        ['sequence' => 31, 'file' => '025_commercial_implementation_checklist.sql'],
        ['sequence' => 32, 'file' => '026_fix_implementation_manual_checklist_table.sql'],
        ['sequence' => 33, 'file' => '027_guided_client_onboarding.sql'],
        ['sequence' => 34, 'file' => '028_backup_automation_n8n.sql'],
        ['sequence' => 35, 'file' => '029_smart_calendar_availability_n8n.sql'],
        ['sequence' => 36, 'file' => '030_google_calendar_availability_modes.sql'],
        ['sequence' => 37, 'file' => '031_optimize_conversation_messages_index.sql'],
        ['sequence' => 38, 'file' => '032_conversation_messages_compact_index.sql'],
        ['sequence' => 39, 'file' => '033_customer_company_profile.sql'],
        ['sequence' => 40, 'file' => '034_notification_preferences_and_alerts.sql'],
        ['sequence' => 41, 'file' => '035_admin_company_tracking.sql'],
        ['sequence' => 42, 'file' => '036_security_access_enforcement.sql'],
        ['sequence' => 43, 'file' => '037_admin_commercial_crm_reports.sql'],
        ['sequence' => 44, 'file' => '038_ai_reaction_preferences.sql'],
        ['sequence' => 45, 'file' => '039_tenant_health_diagnostics.sql'],
        ['sequence' => 46, 'file' => '040_conversation_flow_contact_groups.sql'],
        ['sequence' => 47, 'file' => '041_calendar_google_full_cycle.sql'],
        ['sequence' => 48, 'file' => '042_payment_reconciliation_external_providers.sql'],
        ['sequence' => 49, 'file' => '043_ai_reprocess_schedule.sql'],
        ['sequence' => 50, 'file' => '044_ai_pending_failures_message_link.sql'],
        ['sequence' => 51, 'file' => '045_ai_webhook_ingestion_resilience.sql'],
        ['sequence' => 52, 'file' => '046_calendar_conversational_slot_selection.sql'],
        ['sequence' => 53, 'file' => '047_backup_automation_reliability.sql'],
        ['sequence' => 54, 'file' => '048_reporting_metrics_foundation.sql'],
        ['sequence' => 55, 'file' => '049_operational_resolution_communications.sql'],
        ['sequence' => 56, 'file' => '050_human_takeover_customer_context.sql'],
        ['sequence' => 57, 'file' => '051_operational_evidence_status.sql'],
        ['sequence' => 58, 'file' => '052_ai_usage_and_after_hours_recovery.sql'],
        ['sequence' => 59, 'file' => '053_ai_quota_limit_repair.sql'],
        ['sequence' => 60, 'file' => '054_ai_metrics_and_delivery_telemetry.sql'],
        ['sequence' => 61, 'file' => '055_multi_whatsapp_agent_routing.sql'],
        ['sequence' => 62, 'file' => '056_n8n_agenda_event_contract.sql'],
        ['sequence' => 63, 'file' => '057_calendar_modality_before_availability.sql'],
        ['sequence' => 64, 'file' => '058_client_communication_center.sql'],
        ['sequence' => 65, 'file' => '059_contact_identity_confidence.sql'],
        ['sequence' => 66, 'file' => '060_free_trial_guided_first_access.sql'],
        ['sequence' => 67, 'file' => '061_onboarding_calendar_modes.sql'],
        ['sequence' => 68, 'file' => '062_prompt_studio_and_versions.sql'],
        ['sequence' => 69, 'file' => '063_message_governance_evolution_realtime.sql'],
        ['sequence' => 70, 'file' => '063_message_governance_evolution_realtime_compat.sql'],
        ['sequence' => 71, 'file' => '064_professional_conversation_assignment_compat.sql'],
        ['sequence' => 72, 'file' => '065_professional_calendar_profiles_compat.sql'],
        ['sequence' => 73, 'file' => '066_contact_schedule_overlap_guard_compat.sql'],
        ['sequence' => 74, 'file' => '067_operational_history_metrics_compat.sql'],
        ['sequence' => 75, 'file' => '068_conversation_service_cycles_compat.sql'],
        ['sequence' => 76, 'file' => '069_service_cycle_recovery_compat.sql'],
        ['sequence' => 77, 'file' => '070_conversation_cycle_status_sync_compat.sql'],
        ['sequence' => 78, 'file' => '071_utc_datetime_contract_compat.sql'],
        ['sequence' => 79, 'file' => '072_security_session_webhook_hardening.sql'],
        ['sequence' => 80, 'file' => '073_operational_monitoring_alert_delivery.sql'],
        ['sequence' => 81, 'file' => '074_conversation_message_attachments.sql'],
        ['sequence' => 82, 'file' => '075_scheduled_reports_and_deliveries.sql'],
        ['sequence' => 83, 'file' => '076_evolution_instance_management.sql'],
        ['sequence' => 84, 'file' => '077_ai_efficiency_foundation.sql'],
        ['sequence' => 85, 'file' => '078_contact_avatar_refresh.sql'],
        ['sequence' => 86, 'file' => '079_ai_efficiency_phase2_and_report_cleanup.sql'],
        ['sequence' => 87, 'file' => '080_ai_memory_and_usage_intelligence.sql'],
        ['sequence' => 88, 'file' => '081_ai_cost_attribution.sql'],
        ['sequence' => 89, 'file' => '082_ai_budget_governance.sql'],
        ['sequence' => 90, 'file' => '083_ai_commercial_margin.sql'],
        ['sequence' => 91, 'file' => '084_ai_profitability_history.sql'],
        ['sequence' => 92, 'file' => '085_ai_commercial_attention_queue.sql'],
        ['sequence' => 93, 'file' => '086_plan_ai_mode_and_commitment.sql'],
        ['sequence' => 94, 'file' => '087_webhook_security_events.sql'],
        ['sequence' => 95, 'file' => '088_payment_reconciliation_schema_compat.sql'],
        ['sequence' => 96, 'file' => '089_schema_migrations_registry.sql'],
        ['sequence' => 97, 'file' => '090_crm_conversation_automation.sql'],
        ['sequence' => 98, 'file' => '091_after_hours_monitor_and_quote_requests.sql'],
        ['sequence' => 99, 'file' => '092_notification_orchestration.sql'],
        ['sequence' => 100, 'file' => '093_public_signup_asaas_trial.sql'],
        ['sequence' => 101, 'file' => '094_normalize_asaas_api_base_url.sql'],
        ['sequence' => 102, 'file' => '095_public_signup_pix_qrcode.sql'],
        ['sequence' => 103, 'file' => '096_public_signup_coupons.sql'],
        ['sequence' => 104, 'file' => '097_evolution_operational_alert_suppression.sql'],
        ['sequence' => 105, 'file' => '098_operational_queue_release.sql'],
    ],
];
