<?php
use App\Core\Csrf; use App\Core\Router; use App\Core\View;
$tenants=$data['tenants']??[];$history=$data['history']??[];$summary=$data['summary']??[];
$prefillTenant=(int)($prefillTenant??0);$prefillIncident=(int)($prefillIncident??0);$prefillType=(string)($prefillType??'');
?>
<section class="admin-module-hero communications-hero"><div><span class="eyebrow">Operação RS</span><h2>Comunicados</h2><p>Avise clientes pelo próprio RS Connect e mantenha WhatsApp/e-mail no mesmo histórico de comunicação.</p></div><div class="hero-actions"><span class="badge badge-active"><?= (int)($summary['sent']??0) ?> comunicado(s)</span><span class="badge"><?= (int)($summary['read']??0) ?> leitura(s)</span></div></section>
<div class="communications-layout">
<section class="card communication-compose"><div class="section-heading"><div><span class="eyebrow">Novo comunicado</span><h2>Mensagem para clientes</h2><p class="muted-text">O canal interno é entregue imediatamente. Os canais externos ficam registrados e preparados para o provedor administrativo.</p></div></div>
<form method="post" action="<?= View::e(Router::url('/comunicados/send')) ?>"><?= Csrf::input() ?>
<div class="form-grid two"><label>Tipo<select class="input" name="communication_type"><option value="information">Informação</option><option value="maintenance">Manutenção</option><option value="attention">Atenção</option><option value="incident" <?= $prefillType==='incident'?'selected':'' ?>>Incidente</option><option value="resolved" <?= $prefillType==='resolved'?'selected':'' ?>>Resolvido</option></select></label><label>Público<select class="input" name="audience_type"><option value="selected">Empresas selecionadas</option><option value="all">Todas as empresas</option><?php if($prefillIncident>0):?><option value="incident" selected>Empresas do incidente</option><?php endif;?></select></label></div>
<input type="hidden" name="incident_id" value="<?= $prefillIncident ?>">
<label>Título<input class="input" name="title" maxlength="160" required placeholder="Ex.: Instabilidade temporária na agenda"></label>
<label>Mensagem<textarea class="input" name="message" rows="6" required placeholder="Explique o impacto em linguagem clara, sem expor detalhes técnicos internos."></textarea></label>
<div class="communication-tenant-picker"><strong>Destinatários</strong><div class="communication-tenant-list"><?php foreach($tenants as $tenant):?><label><input type="checkbox" name="tenant_ids[]" value="<?= (int)$tenant['id'] ?>" <?= $prefillTenant===(int)$tenant['id']?'checked':'' ?>><span><strong><?= View::e((string)$tenant['name']) ?></strong><small><?= View::e((string)($tenant['email']??'')) ?><?= !empty($tenant['admin_phone'])?' · '.View::e((string)$tenant['admin_phone']):'' ?></small></span></label><?php endforeach;?></div></div>
<div class="communication-channels"><label class="is-fixed"><input type="checkbox" checked disabled><span><strong>RS Connect</strong><small>Sininho + histórico do cliente.</small></span></label><label><input type="checkbox" name="channel_whatsapp" value="1"><span><strong>WhatsApp administrativo</strong><small>Preparado; não depende da instância do cliente.</small></span></label><label><input type="checkbox" name="channel_email" value="1"><span><strong>E-mail</strong><small>Preparado para o transportador da RS.</small></span></label></div>
<div class="form-actions"><button class="btn btn-primary" type="submit">Enviar comunicado</button></div></form></section>
<section class="card communication-guidance"><span class="eyebrow">Boa prática</span><h2>Técnico para a RS, claro para o cliente</h2><p>Evite enviar mensagens como “N8N_CALLBACK_TOKEN mismatch”. Prefira “Identificamos uma instabilidade temporária na integração e já estamos atuando”.</p><div class="communication-template"><strong>Incidente</strong><p>Identificamos uma indisponibilidade temporária no serviço. Os dados permanecem preservados e estamos trabalhando na normalização.</p></div><div class="communication-template"><strong>Normalização</strong><p>O funcionamento foi normalizado. O serviço voltou a operar normalmente.</p></div></section>
</div>
<section class="card"><div class="section-heading"><div><span class="eyebrow">Histórico</span><h2>Envios e leituras</h2></div></div><div class="table-responsive"><table><thead><tr><th>Data</th><th>Tipo</th><th>Título</th><th>Destinatários</th><th>Lidos</th><th>WhatsApp</th><th>E-mail</th></tr></thead><tbody><?php foreach($history as $row):?><tr><td><?= View::e((string)($row['sent_at']??$row['created_at']??'')) ?></td><td><span class="badge"><?= View::e((string)($row['communication_type']??'')) ?></span></td><td><strong><?= View::e((string)($row['title']??'')) ?></strong></td><td><?= (int)($row['recipients']??0) ?></td><td><?= (int)($row['read_count']??0) ?></td><td><?= (int)($row['whatsapp_pending']??0)>0?'Aguardando configuração':'—' ?></td><td><?= (int)($row['email_pending']??0)>0?'Aguardando configuração':'—' ?></td></tr><?php endforeach;?><?php if(!$history):?><tr><td colspan="7">Nenhum comunicado enviado.</td></tr><?php endif;?></tbody></table></div></section>
